[package]
name = "rust-libloading"
version = "0.1.0"
authors = ["Kyle M. Douglass <kyle.m.douglass@gmail.com>"]
edition = "2018"
exclude = ["ffi-test"]

[dependencies]
libc = "0.2"
libloading = "0.5"
